counter/urls.py
from django.urls import path
from . import views
urlpatterns = [ 
    path('<int:form_id>/', views.count, name='count')
]

image_handling/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.upload, name='upload'),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

objs_counter/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main_app.urls', 'main_app'), namespace='main_app')),
    path('upload/', include(('image_handling.urls', 'image_handling'), namespace='image_handling')),
    path('count/', include(('counter.urls', 'counter'), namespace='counter')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

counter/models.py
from django.db import models
from image_handling.models import SubmittedFormData  # Import the model associated with image submissions

class DetectionResult(models.Model):
    submission = models.ForeignKey(SubmittedFormData, on_delete=models.CASCADE)
    detected_objects = models.TextField()
    image = models.ImageField(upload_to='detection_results/')  

    # Additional fields, if needed
    detection_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Detection Result #{self.pk} for Form Submission #{self.submission.pk}"

image_handling/models.py
from django.db import models

class SubmittedFormData(models.Model):
    image = models.ImageField(upload_to='uploads/') 
    selected_objects = models.CharField(max_length=255)  

    # Additional fields if needed
    timestamp = models.DateTimeField(auto_now_add=True)  

    # def __str__(self):
    #     return f"Form Submission #{self.pk} - {self.timestamp}"

main_app/models.py
from django.db import models

# Create your models here.

counter/views.py
from django.core.files.base import ContentFile
from django.shortcuts import render, get_object_or_404
from counter.models import DetectionResult
from image_handling.models import SubmittedFormData
from utilities.object_detection import perform_object_detection

def count(request, form_id):
    # Retrieve the SubmittedFormData object based on the form_id
    submission = get_object_or_404(SubmittedFormData, pk=form_id)

    # Access the image field from the retrieved object
    uploaded_image = submission.image

    # Perform object detection logic on the uploaded image
    detection_results = perform_object_detection(uploaded_image.path, submission.selected_objects)
    
    # Create a ContentFile from the image data
    image_data = ContentFile(detection_results["image"], name="prediction.jpg")

    # Create a new DetectionResult instance and associate it with the submission
    detection_result = DetectionResult(submission=submission, detected_objects=detection_results['json'])
    detection_result.image.save("prediction.jpg", image_data)
    
    # Pass the results to the template for rendering
    context = {
        'detection_result': detection_result,
        'count': len(detection_results['json']['predictions'])
    }

    return render(request, 'count/count.html', context)

image_handling/views.py
from django.shortcuts import render, redirect

from image_handling.models import SubmittedFormData


def upload(request):
    if request.method == 'POST':
        uploaded_image = request.FILES.get('image')
        selected_objects = request.POST.getlist('selected_objects')

        if uploaded_image:
            # Save the uploaded image
            uploaded_image_obj = SubmittedFormData(image=uploaded_image, selected_objects=','.join(selected_objects))
            uploaded_image_obj.save()
            
        # Get the ID of the saved object
        saved_object_id = uploaded_image_obj.id

           
        return redirect('counter:count', form_id = saved_object_id)

    # List of object names
    object_names = [
        "person", "bicycle", "car", "motorcycle", "airplane", "bus", "train", "truck", "boat", "traffic light",
        "fire hydrant", "stop sign", "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep", "cow",
        "elephant", "bear", "zebra", "giraffe", "backpack", "umbrella", "handbag", "tie", "suitcase", "frisbee",
        "skis", "snowboard", "sports ball", "kite", "baseball bat", "baseball glove", "skateboard", "surfboard",
        "tennis racket", "bottle", "wine glass", "cup", "fork", "knife", "spoon", "bowl", "banana", "apple",
        "sandwich", "orange", "broccoli", "carrot", "hot dog", "pizza", "donut", "cake", "chair", "couch",
        "potted plant", "bed", "dining table", "toilet", "tv", "laptop", "mouse", "remote", "keyboard",
        "cell phone", "microwave", "oven", "toaster", "sink", "refrigerator", "book", "clock", "vase", "scissors",
        "teddy bear", "hair dryer", "toothbrush"
    ]
    # Pass the object names to the template
    context = {
        'object_names': object_names,
    }
    
    return render(request, 'upload/upload.html', context)

main_app/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home/home.html')

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Objects Detection Counter{% endblock %}</title>

    <!-- Include Bootstrap CSS from CDN -->
<link
       href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
        rel="stylesheet"
    > 

    <!-- Custom CSS for Background and Styling -->
    <style>
        /* Customize the background color or add a background image */
        body {
            background-color: #f4f4f4; /* Light gray background color */
           
        }

        .text-primary {
            color: #007bff; /* Blue text color */
        }
    </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">Objects Counter</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container mt-4">
    {% block content %}{% endblock %}
</div>

</body>
</html>

templates/count/count.html
{% extends 'base/base.html' %}

{% block content %}
  <div class="container mt-5">
    <div class="row">
      <div class="col-md-6">
        <h1 class="display-4">Object Detection Results</h1>

        <!-- Display the number of detected objects -->
        <div class="mb-4">
          <h2>Number of Detected Objects: {{ count }}</h2>
        </div>

        <!-- Link to go back to the upload page -->
        <div class="text-center">
          <a href="{% url 'image_handling:upload' %}" class="btn btn-primary">Upload Another Image</a>
        </div>
      </div>
      <div class="col-md-6">
        <!-- Display the detected image -->
        <h2 class="mb-3">Detected Image:</h2>
        <div class="text-center">
          <img src="{{ detection_result.image.url }}" alt="Detected Image" class="img-fluid rounded">
        </div>
      </div>
    </div>

    <!-- Visualize detected objects as a list -->
    <div class="mt-5">
      <h2 class="mb-3">Detected Objects:</h2>
      <ul class="list-group">
        {% for prediction in detection_result.detected_objects.predictions %}
          <li class="list-group-item">
            <strong>{{ prediction.class }}</strong> - Confidence: {{ prediction.confidence }}
          </li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

templates/home/home.html
{% extends "base/base.html" %}

{% block title %}Home Page{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8 text-center">
            <h1 class="display-4">Welcome to Object Detection</h1>
            <p class="lead">Detect objects in images with ease.</p>
            <hr class="my-4">
            <p>Upload an image and choose the objects to count.</p>
            <a class="btn btn-primary btn-lg" href="/upload/" role="button">Get Started</a>
        </div>
    </div>
</div>
{% endblock %}

templates/upload/upload.html
{% extends "base/base.html" %}

{% block title %}Upload Image{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Upload an Image</h2>
    <form action="/upload/" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="imageUpload" class="form-label">Select an Image</label>
            <input type="file" class="form-control" id="imageUpload" name="image">
        </div>
        <div class="mb-3">
            <label for="objectSelection" class="form-label">Select Objects to Detect</label>
            <select class="form-select" id="objectSelection" name="selected_objects">
                {% for name in object_names  %}
                <option value="{{ name }}">{{ name }}</option>
             {% endfor %}
            </select>

        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}